{{- range $isDeleteHook := until 2 }}
{{- with $ }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stigatron-prehook
  annotations:
    {{- if eq $isDeleteHook 0 }}
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": hook-failed,hook-succeeded
    {{- else }}
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- end }}
    "helm.sh/hook-weight": "-10"
subjects:
  - kind: ServiceAccount
    name: stigatron-prehook
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: stigatron-prehook
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}