{{- range $isDeleteHook := until 2 }}
{{- with $ }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stigatron-prehook
  annotations:
    {{- if eq $isDeleteHook 0 }}
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": hook-failed
    {{- else }}
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- end }}
    "helm.sh/hook-weight": "-10"
{{- end }}
{{- end }}